version: "3.0"

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
