spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
    url: "${DATABASE_URL}"

amazon:
  s3:
    accessKey:
    secretKey:
